stages:
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build-prod:
  stage: build
  image: node:10
  script:
    - npm install
    - ./node_modules/.bin/vuepress build
    - cp humans.txt .vuepress/dist
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - .vuepress/dist/
  only:
    - master

build-dev:
  stage: build
  image: node:10
  script:
    - npm install
    - ./node_modules/.bin/vuepress build
    - cp humans.txt .vuepress/dist
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - .vuepress/dist/
  only:
    - develop

# upload job, see https://lftp.yar.ru/lftp-man.html
deploy-prod:
  stage: deploy
  image: mwienk/docker-lftp:latest
  script:
    - "[[ ${HIDE_ON_WEB} ]] && { cp robots.txt .vuepress/dist; }"
    - "[[ ${HIDE_ON_WEB} ]] && { cp .htaccess .vuepress/dist; }"
    - lftp -e "mirror -R .vuepress/dist /www/website -envp ; exit;" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
  dependencies:
    - build-prod
  only:
    - master
  when: manual
    
deploy-dev:
  stage: deploy
  image: mwienk/docker-lftp:latest
  script:
    - cp robots.txt .vuepress/dist
    - lftp -e "mirror -R .vuepress/dist /www/website-dev -envp ; exit;" -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST
  dependencies:
    - build-dev
  only:
    - develop