const TECH_ICONS: Record<string, string> = {
  'React': 'i-logos-react',
  'Vue': 'i-logos-vue',
  'Angular': 'i-logos-angular-icon',
  'Redux': 'i-logos-redux',
  'Preact': 'i-logos-preact',
  'Vite': 'i-logos-vitejs',
  'PWA': 'i-logos-pwa',
  'JavaScript': 'i-logos-javascript',
  'TypeScript': 'i-logos-typescript-icon',
  'PHP': 'i-logos-php',
  'Python': 'i-logos-python',
  'Node.js': 'i-logos-nodejs-icon',
  'HTML': 'i-logos-html-5',
  'CSS': 'i-logos-css-3',
  'Nuxt': 'i-logos-nuxt-icon',
  'Nitro': 'i-unjs-nitro',
  'Nuxt 3': 'i-logos-nuxt-icon',
  'Nuxt 4': 'i-logos-nuxt-icon',
  'Nuxt UI': 'i-skill-icons-nuxtjs-dark',
  'NestJS': 'i-logos-nestjs',
  'TypeORM': 'i-logos-typeorm',
  'Vitest': 'i-logos-vitest',
  'FullCalendar': 'i-mdi-calendar-month-outline',
  'rrule': 'i-mdi-repeat-variant',
  'Next.js': 'i-logos-nextjs-icon',
  'Tailwind': 'i-logos-tailwindcss-icon',
  'Docker': 'i-logos-docker-icon',
  'Laravel': 'i-logos-laravel',
  'Git': 'i-logos-git-icon',
  'MySQL': 'i-logos-mysql',
  'PostgreSQL': 'i-logos-postgresql',
  'MongoDB': 'i-logos-mongodb-icon',
  'Redis': 'i-logos-redis',
  'AWS': 'i-logos-aws',
  'Firebase': 'i-logos-firebase',
  'Vercel': 'i-logos-vercel-icon',
  'Netlify': 'i-logos-netlify',
  'jQuery': 'i-logos-jquery',
  'Bootstrap': 'i-logos-bootstrap',
  'Service Worker': 'i-logos-pwa',
  'REST API': 'i-mdi-api',
}

export const TECH_ICON_CLASSES = Object.values(TECH_ICONS)

export function getTechIcon(tech: string): string | null {
  return TECH_ICONS[tech] ?? null
}