name: Setup Environment

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v4
        run_install: false
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Verify pnpm installation
        run: |
          which pnpm
          pnpm --version
          echo "pnpm is installed and accessible."
